# Generated by Django 4.2 on 2023-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.BooleanField(default=False, verbose_name='Менеджер')),
                ('worker', models.BooleanField(default=True, verbose_name='Рабочий')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('personnel_number', models.PositiveIntegerField(default=1)),
                ('payroll_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Сотрудник',
            },
        ),
    ]
