# Generated by Django 4.2 on 2023-05-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='salary_index',
            field=models.FloatField(default=1.0, verbose_name='Индекс зарплаты'),
        ),
    ]
