# Generated by Django 4.2 on 2023-05-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_unit_salary_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_at', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('arrived', 'Пришел на работу'), ('gone', 'Ушел с работы'), ('vacation', 'В отпуске'), ('back', 'Вернулся с отпуска')], default='arrived', max_length=100, verbose_name='Статус работника')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.unit', verbose_name='Работник')),
            ],
            options={
                'verbose_name_plural': 'Статус сотрудника',
            },
        ),
    ]
